/*
 * File: public/app/model/KPI.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('taskBoard.model.KPI', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],
    fields: [
        {
            name: 'id',
            type: 'number',
        },
        {
            name: 'indicator',
            type: 'string',
            persist:false
        },
        {
            name: 'evaluated',
            persist:false
        },
        {
            name: 'value_fact'
        },
        {
            name: 'value_target'
        },
        {
            name: 'month',
            type:'date',
            dateFormat:'m-Y',
        },
        {
            name: 'is_asc',
            persist:false
        },
        {
            name: 'targetFact',
            calculate:function(data){
                if(data.value_fact && data.value_target )
                {
                    if (data.is_asc)
                        return Math.round((data.value_fact/data.value_target)*100);
                    else
                        return Math.round((data.value_target/data.value_fact)*100);
                }
            }
        }
    ]
});