/*
 * File: public/app/model/Purpose.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('taskBoard.model.Purpose', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'number',
            name: 'id'
        },
        {
            type: 'string',
            name: 'name'
        },

        {
            name: 'responsible',
            type:'auto'
        },
        {
            name:'limitation',
            type:'date',
            dateFormat:'Y-m-d'
        }
        ,
        {
            type: 'string',
            name: 'comment'
        }
        ,
        {
            type: 'number',
            name: 'status'
        }
    ]
});