 /*
 * File: public/app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('taskBoard.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'taskBoard.view.MyViewportViewModel',
        'taskBoard.view.MyViewportViewController',
        'taskBoard.view.TaskGrid',
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.feature.GroupingSummary',
        'Ext.XTemplate',
        'Ext.grid.column.Date',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.column.Widget',
        'Ext.sparkline.Pie',
        'Ext.grid.plugin.RowExpander',
        'Ext.form.field.Number',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.series.Bar',
        'Ext.chart.interactions.PanZoom',
        'Ext.chart.legend.Legend',
        'Ext.chart.series.Line',
        'Ext.chart.axis.Numeric',
        'Ext.form.field.TextArea',
        'Ext.tab.Tab',
        'Ext.tab.Bar',
        'Ext.grid.filters.Filters',
        'Ext.picker.Date',
        'Ext.picker.Month'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },
    reference: '_task',
    height: 250,
    width: 400,
    layout: 'fit',
    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            header: {
                titlePosition: 1,
                items: [
                    {
                        xtype:'container',

                        items:[
                            {
                                xtype: 'button',
                                iconCls: 'icon-button-navigation',
                                listeners: {
                                    click: 'onButtonClick'
                                },
                            },
                            {
                                xtype: 'label',
                                cls: 'my-panel-header-title',
                                listeners: {
                                    render: 'onLabelRender'
                                },
                                padding:'10 10 10 10'

                            }
                        ]
                    },
                    {
                        xtype: 'tbspacer',
                    },
                    {
                        xtype: 'label',
                        cls:'my-panel-header-title',
                        listeners: {
                            render: function(component) {
                                component.setHtml(Ext.util.Cookies.get('user'));
                            }
                        }
                    }
                ],
            },
            title:{
                text:'Визуальное управление эффективностью',
                cls:'my-main-title',
                height:30,
            },
            titleAlign: 'center',
            items: [
                {
                    xtype: 'tabpanel',
                    reference: '_navigationMenu',
                    titleRotation: '1',
                    activeTab: 0,
                    minTabWidth: 200,
                    tabPosition: 'left',
                    tabRotation: '',
                    items: [
                        {
                            xtype: 'panel',
                            reference: '_main',
                            iconCls: 'icon-button-home',
                            title: 'Главная',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems:{
                                xtype: 'toolbar',
                                dock: 'top',
                                cls:'my-toolbar-t',
                                border: true,
                                items: [
                                    {
                                        xtype: 'combobox',
                                        validator: function(value) {
                                            return(value.trim().length>0)?true:"Поле не может быть пустым";
                                        },
                                        reference: '_department',
                                        alias:'combobox.department',
                                        width: 300,
                                        emptyText: 'Выберите подразделение',
                                        displayField: 'department_name',
                                        bind: {store:'{Department}'},
                                        valueField: 'id',
                                        allowBlank: false,
                                        listeners:{
                                            select: 'onDepartmentSelect'
                                        }
                                    }

                                ]
                            },
                            //cls:'my-panel-b',
                            /**/
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 3,
                                    resizable: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    cls:'my-panel-t',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            //flex: 1,
                                            width:'20%',
                                            collapseDirection: 'left',
                                            collapsible: true,
                                            hideCollapseTool: true,
                                            resizable:true,
                                            title: {
                                                text: 'КПЭ',

                                                cls: 'my-panel-header-title'
                                            },

                                            titleAlign:'center',
                                            titleCollapse: true,
                                            cls:'my-panel-r',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'kpi-grid',
                                                    bind: {
                                                        department: '{_department}'
                                                    }
                                                },
                                                {
                                                    xtype: 'panel',
                                                    height: 450,
                                                    width: 600,
                                                    collapsed: false,
                                                    collapseDirection: 'top',
                                                    collapsible: true,
                                                    hideCollapseTool: true,
                                                    titleCollapse: true,
                                                    cls:'my-panel-t',
                                                    title: {
                                                        text:'Идея',

                                                        cls: 'my-panel-header-title'
                                                    },
                                                    titleAlign:'center',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            height: 200,
                                                            width: 200,
                                                            flex:1,
                                                            xtype: 'cartesian',
                                                            animate: true,
                                                            shadow: true,
                                                            bind: {
                                                                store: '{ideaQuarter}'
                                                            },
                                                            axes: [{
                                                                type: 'numeric',
                                                                position: 'left',
                                                                fields: ['engagement'],
                                                                minimum: 0,
                                                                maximum: 110,
                                                                hidden:true,

                                                            }, {
                                                                type: 'category',
                                                                position: 'bottom',
                                                                fields: ['quarter'],
                                                                minimum: -1,
                                                                maximum: 4,
                                                                title: 'Вовлеченность,%',
                                                                label:{rotate:{degrees:45}},
                                                            }],
                                                            series: [{
                                                                type: 'line',
                                                                title: 'Charges',
                                                                xField: 'quarter',
                                                                yField: ['engagement'],
                                                                marker: {
                                                                    radius: 4
                                                                },
                                                                label:{
                                                                    display:'insideStart',
                                                                    field:'engagement',
                                                                    position:'bottom'
                                                                },
                                                                showMarkers:true

                                                            }]
                                                        }
                                                        ,
                                                        {
                                                            height: 250,
                                                            width: 400,
                                                            xtype: 'cartesian',
                                                            flipXY:true,
                                                            style: 'background:#fff',
                                                            animate: true,
                                                            shadow: true,
                                                            flex:2,
                                                            bind: {
                                                                store: '{ideaQuarter}'
                                                            },
                                                            legend: {
                                                                position: 'right'
                                                            },
                                                            animate: true,
                                                            shadow: true,
                                                            legend: {
                                                                position: 'right'
                                                            },
                                                            axes: [{
                                                                type: 'numeric',
                                                                position: 'bottom',
                                                                fields: ['filed', 'approved', 'implemented'],
                                                                minimum: 0,
                                                                majorTickSteps: 1,

                                                                grid: true,
                                                                title: 'Колиичество идей'
                                                            }, {
                                                                type: 'category',
                                                                position: 'left',
                                                                fields: ['quarter']
                                                            }],
                                                            series: [{
                                                                type: 'bar',
                                                                axis: 'bottom',
                                                                xField: 'quarter',
                                                                yField: ['filed', 'approved', 'implemented'],
                                                                title: [
                                                                    'Подано',
                                                                    'Одобрено',
                                                                    'Реализовано'
                                                                ]
                                                            }]
                                                            ,
                                                            interactions: [
                                                                {
                                                                    type: 'panzoom'
                                                                }
                                                            ],
                                                            legend: {
                                                                xtype: 'legend',
                                                                docked: "bottom"
                                                            }
                                                        }
                                                    ]}

                                            ]
                                        },
                                        { xtype: 'panel',
                                            //flex: 3,
                                            width:'60%',
                                            resizable: true,
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [{
                                                    xtype: 'task-grid',
                                                    bind: {
                                                        department: '{_department}'
                                                    }
                                            }, {
                                                    xtype: 'risk-grid',
                                                    bind: {
                                                        department: '{_department}'
                                                    }
                                            }
                                        ]},
                                        {
                                            xtype: 'panel',
                                            //flex: 1,
                                            width:'20%',
                                            collapsed: false,
                                            collapseDirection: 'right',
                                            collapsible: true,
                                            resizable: true,
                                            hideCollapseTool: true,
                                            title: {
                                                text:'HSE',
                                                cls: 'my-panel-header-title'
                                            },
                                            titleAlign:'center',
                                            titleCollapse: true,
                                            cls:'my-panel-l',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    height:'25%',
                                                    reference: '_hsePanel',
                                                    resizable: true,
                                                    layout: 'border',
                                                    items:[
                                                        {
                                                            xtype: 'container',
                                                            style:'background:white;'
                                                        }
                                                    ],

                                                },
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 2,
                                                    height:"50%",
                                                    border: false,
                                                    resizable: true,
                                                    title: {
                                                        text:'УПЦ',
                                                        cls: 'my-panel-header-title'
                                                    },
                                                    collapsed: false,
                                                    collapseDirection: 'bottom',
                                                    collapsible: true,
                                                    hideCollapseTool: true,
                                                    titleCollapse: true,
                                                    cls:'my-panel-t',
                                                    titleAlign: 'center',
                                                    //hideHeaders: true,
                                                    bind: {
                                                        store: '{Purpose}'
                                                    },
                                                    columns: {
                                                            items:[
                                                            {
                                                                xtype: 'gridcolumn',
                                                                flex: 3,
                                                                dataIndex: 'name',
                                                                text: 'Цель',
                                                                cellWrap:true
                                                            },
                                                            {
                                                                xtype: 'datecolumn',
                                                                flex: 1,
                                                                dataIndex: 'limitation',
                                                                text: 'Срок',
                                                                format: 'd.m.y',
                                                            },
                                                            {
                                                                xtype: 'datecolumn',
                                                                flex: 1,
                                                                dataIndex: 'status',
                                                                hidden:true,
                                                                text: 'Статус',
                                                                renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                                    var val=Sga.renderColumnVal('StatusStore','id',value,'text',view);
                                                                    return val;
                                                                },
                                                            }

                                                        ]
                                                    }
                                                ,
                                                plugins: [
                                                    {
                                                        ptype: 'rowexpander',
                                                        rowBodyTpl: [
                                                            '<p>{comment}</p>'
                                                        ]
                                                    }
                                                ],
                                                    listeners: {
                                                        afterrender: 'onPurposePanelAfterRender',
                                                            celldblclick:'onPurposeCellDblClick'
                                                    }
                                                },
/*
                                                {
                                                    xtype: 'panel',
                                                    height:150,
                                                    reference: '_thanksPanel',
                                                    resizable: true,
                                                    layout: 'border',
                                                    collapsed: false,
                                                    collapseDirection: 'bottom',
                                                    collapsible: true,
                                                    hideCollapseTool: true,
                                                    titleCollapse: true,
                                                    cls:'my-panel-t',
                                                    title: {
                                                        text:'Благодарность',
                                                        cls: 'my-panel-header-title'
                                                    },
                                                    titleAlign: 'center',
                                                    items:[

                                                        {
                                                            xtype: 'thanks-grid',
                                                            bind: {
                                                                department: '{_department}'
                                                            }
                                                        }
                                                    ],

                                                }*/,
                                                {
                                                    xtype: 'thanks-grid',
                                                    bind: {
                                                        department: '{_department}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            tabConfig: {
                                xtype: 'tab',
                                height: 50
                            }
                        },
                        {
                            xtype: 'panel',
                            iconCls: 'icon-button-setting',
                            title: 'Управление',
                            titleAlign: 'center',
                            tabConfig: {
                                xtype: 'tab',
                                height: 50
                            },
                            items:[
                                { xtype: 'panel',
                                    flex: 3,
                                    resizable: true,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [{
                                        xtype: 'control-panel'
                                    }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            iconCls: 'icon-button-user',
                            title: 'Настройки',
                            tabConfig: {
                                xtype: 'tab',
                                height: 50
                            }
                        },
                        {
                            xtype: 'panel',
                            layout: 'fit',
                            iconCls: 'icon-button-user',
                            title: 'Планерка',
                            tabConfig: {
                                xtype: 'tab',
                                height: 50
                            },
                            items: [{ xtype: 'panel',
                                flex: 3,

                                layout: {
                                    type: 'vbox',
                                    align: 'stretch'
                                },
                                items: [{
                                    xtype: 'appointment-panel',
                                    height:'100%'
                                }
                                ]
                            }]
                        }
                    ],
                    tabBar: {
                        xtype: 'tabbar',
                        width: 0
                    }
                }
            ]

        }
    ],
    listeners: {
        load: 'onPanelShow'
    },
});