/*
 * File: public/app/view/PurposeEditModalViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('taskBoard.view.PurposeEditModalViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.purposeeditmodal',


    save: function (button, e, eOpts) {
        var form = button.up('form'),
            window = form.up('window');
        //rec = this.getViewModel().get('currentTaskRec');
        Ext.StoreManager.lookup('PurposeStore').sync();
        //rec.commit();
        window.close();
    },

    cancel: function (button, e, eOpts) {
        var form = button.up('form'),
            window = form.up('window'),
            rec = this.getViewModel().get('currentPurposeRec');
        rec.reject();
        window.close();
    }
});