/*
 * File: public/app/view/PurposeEditModal.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('taskBoard.view.PurposeEditModal', {
    extend: 'Ext.window.Window',
    alias: 'widget.purposeeditmodal',

    requires: [
        'taskBoard.view.PurposeEditModalViewModel',
        'taskBoard.view.PurposeEditModalViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.form.field.Date',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.grid.plugin.CellEditing',
        'Ext.toolbar.Toolbar'
    ],
    /*
        config: {
            currentTaskRec: null
        },*/

    controller: 'purposeeditmodal',
    viewModel: {
        type: 'purposeeditmodal'
    },

    modal: true,
    height: 500,
    width: 800,
    layout: 'fit',
    closeAction: 'hide',
    closable:false,
    plain: true,
    bind: {
        title: '{title}'
    }
    ,
    items: [
        {
            xtype: 'form',
            reference: '_formRiskEdit',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textareafield',
                    reference: '_riskName',
                    width: '80%',
                    fieldLabel: 'Цель',
                    bind: '{currentPurposeRec.name}'
                },
                {
                    xtype: 'combobox',
                    validator: function(value) {
                        return(value.trim().length>0)?true:"Поле не может быть пустым";
                    },
                    reference: '_riskUser',
                    width: 600,
                    fieldLabel: 'Ответственный',
                    multiSelect:true,
                    allowBlank: false,
                    emptyText: 'Выберите ответственного',
                    displayField: 'full_name',
                    bind: {store:'{Users}',value:'{currentPurposeRec.user_id}'},
                    valueField: 'id',
                },
                {
                    xtype: 'combobox',
                    reference: '_riskStatus',
                    width: 300,
                    fieldLabel: 'Текущий статус',
                    emptyText: 'Выберите статус',
                    displayField: 'text',
                    bind: {
                        store: '{Status}',
                        value:'{currentPurposeRec.status}'
                    },
                    valueField: 'id',
                },
                {
                    xtype: 'datefield',
                    reference: '_datePurpose',
                    fieldLabel: 'Дата',
                    format: 'd.m.y',
                    bind: '{currentPurposeRec.limitation}'
                }
                ,
                {
                    xtype: 'textareafield',
                    reference: '_textComment',
                    width: '80%',
                    fieldLabel: 'Комментарий',
                    bind: '{currentPurposeRec.comment}'
                }

            ],
            bbar:[{
                xtype: 'button',
                text: 'Сохранить',
                buttonAlign:'left',
                docked: 'left',
                listeners: {
                    click: 'save'
                }

            },
                '->',
                {
                    xtype: 'button',
                    text: 'Отмена',
                    docked: 'right',
                    listeners: {
                        click: 'cancel'
                    },
                }]


        }
    ]/*,
    listeners: {
        show: 'onWindowShow'
    }*/

});