/*
 * File: app/view/taskOperModalViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Wdl.view.TaskEditModalViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.taskeditmodal',

    requires: [
        'Ext.data.Store',
        'Ext.data.field.Date',
        'Ext.data.field.Integer',
        'Ext.data.proxy.Direct',
        'Wdl.DirectAPI',
        'Ext.data.reader.Json',
        'Ext.data.field.String'
    ],

    stores: {
        Users: {
            autoLoad: true,
            proxy: {
                type: 'direct',
                directFn: 'Task.getUsers',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'full_name'
                },
                {
                    name: 'department'
                },
                {
                    name: 'username'
                },
                {
                    name: 'phone'
                },
                {
                    name: 'id'
                }
            ]
        },
        task: {
            fields: [
                {
                    type: 'string',
                    name: 'name'
                },
                {
                    type: 'date',
                    name: 'date'
                },
                {
                    name: 'status'
                },
                {
                    type: 'string',
                    name: 'comment'
                },
                {
                    name: 'fullName'
                },
                {
                    name: 'user_id'
                }
            ]
        },

    }

});