/*
 * File: public/app/view/TaskEidtModal.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('taskBoard.view.TaskEditModal', {
    extend: 'Ext.window.Window',
    alias: 'widget.taskeditmodal',

    requires: [
        'taskBoard.view.TaskEditModalViewModel',
        'taskBoard.view.TaskEditModalViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.form.field.Date',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.grid.plugin.CellEditing',
        'Ext.toolbar.Toolbar'
    ],
/*
    config: {
        currentTaskRec: null
    },*/

    controller: 'taskeditmodal',
    viewModel: {
        type: 'taskeditmodal'
    },

    modal: true,
    height: 500,
    itemId: 'mywindow',
    width: 800,
    layout: 'fit',
    closeAction: 'hide',
    closable:false,
    plain: true,
    bind: {
        title: '{title}'
    }
    ,
    items: [
        {
            xtype: 'form',
            reference: '_formTaskEdit',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textareafield',
                    reference: '_taskName',
                    width: '80%',
                    fieldLabel: 'Задача',
                    bind: '{currentTaskRec.name}',
                    allowBlank: false
                },
                {
                    xtype: 'combobox',
                    validator: function(value) {
                        return(value.trim().length>0)?true:"Поле не может быть пустым";
                    },
                    reference: '_user',
                    width: 600,
                    fieldLabel: 'Ответственный',
                    emptyText: 'Выберите ответственного',
                    displayField: 'full_name',
                    bind: {store:'{Users}',value:'{currentTaskRec.user_id}'},
                    valueField: 'id',
                    allowBlank: false,
                    /*listeners:{
                        select:'onComboboxUserSelect'
                    }*/
                },
                {
                    xtype: 'tagfield',
                    reference: '_kpis',
                    width: 600,
                    fieldLabel: 'Влияет на КПЭ',
                    emptyText: 'Выберите КПЭ',
                    displayField: 'indicator',
                    multiSelect:true,
                    bind: {
                        store: '{KPI}',
                        value:'{currentTaskRec.kpi}'
                    },
                    valueField: 'id',

                },
                {
                    xtype: 'tagfield',
                    reference: '_purpose',
                    width: 600,
                    fieldLabel: 'Влияет на УПЦ',
                    emptyText: 'Выберите УПЦ',
                    displayField: 'name',
                    multiSelect:true,
                    bind: {
                        store:'{Purpose}',
                        value:'{currentTaskRec.purpose}'
                    },
                    valueField: 'id',


                },
                {
                    xtype: 'numberfield',
                    reference: '_taskProgress',
                    width: '80%',
                    fieldLabel: 'Прогресс',
                    minValue:'0',
                    maxValue:'100',
                    bind: '{currentTaskRec.progress}'
                },
                {
                    xtype: 'combobox',
                    reference: '_taskStatus',
                    width: 300,
                    fieldLabel: 'Текущий статус',
                    //emptyText: 'Выберите статус',
                    displayField: 'text',
                    bind: {
                        store: '{Status}',
                        value:'{currentTaskRec.status}'
                    },
                    value:1,
                    forceSelection: true,
                    //allowBlank: false,
                    valueField: 'id',
                },
                {
                    xtype: 'datefield',
                    reference: '_dateTask',
                    fieldLabel: 'Дата',
                    format: 'd.m.y',
                    bind: '{currentTaskRec.date}',
                    allowBlank: false
                },
                {
                    xtype: 'textareafield',
                    reference: '_textComment',
                    width: '80%',
                    fieldLabel: 'Комментарий',
                    bind: '{currentTaskRec.comment}'
                }

            ],
            bbar:[{
                xtype: 'button',
                text: 'Сохранить',
                buttonAlign:'left',
                docked: 'left',
                listeners: {
                    click: 'save'
                }

            },
                '->',
                {
                    xtype: 'button',
                    text: 'Отмена',
                    docked: 'right',
                    listeners: {
                        click: 'cancel'
                    },
                }]


        }
    ]
});