/*
 * File: public/app/view/TaskEditModalViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('taskBoard.view.ThanksEditModalViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.thankseditmodal',


    save: function (button, e, eOpts) {
        var form = button.up('form'),
            window = form.up('window'),
            store=Ext.StoreManager.lookup('ThanksStore'),
            storeUser=Ext.StoreManager.lookup('UserStore'),
            rec = this.getViewModel().get('currentThanksRec'),
            users=rec.get('respected'),
            fullname=[]
            users.forEach(function(userId){
                recordUser=storeUser.findRecord('id',userId);
                fullname.push(recordUser.get('full_name'));
            })


        if (form.isValid()){
            rec.set('respectedName',fullname.join(','));
            if (rec.isPhantom()) {
                store.add(rec);
            }
            store.sync({
                failure : function(){
                    store.rejectChanges();
                }
            });
            window.close();
        }
    },

    cancel: function (button, e, eOpts) {
        var form = button.up('form'),
            window = form.up('window'),
            rec = this.getViewModel().get('currentThanksRec');
        rec.reject();
        window.close();
    }
});